language: bash

services: docker

install:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose --version
    - make docker/docker-compose.env
    - docker-compose --project-name security up -d console

before_script:
    - docker ps

script:
    - docker exec --user=gitlab-runner security_console make test
    - docker exec --user=gitlab-runner security_console make cs-check
