language: bash

services: docker

install:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose --version
    - make docker/docker-compose.env

script:
    - ls -la /home/travis/build/mdeblaise/TestTravis/docker/
    - docker-compose ps
    - docker-compose up -d