# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
                memory:
                    users:
                        toto:
                            password: toto
                            roles: 'ROLE_USER'
                        admin:
                            password: admin
                            roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout:
                path:   /logout
                target: /
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
    #    # require ROLE_ADMIN for /admin*
    #    - { path: ^/admin, roles: ROLE_ADMIN }
    #    - { path: ^/, roles: ROLE_USER }

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt